# Generated by Django 4.2 on 2023-04-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='theme',
            field=models.CharField(choices=[('btn-primary', 'BLEU'), ('btn-danger', 'ROUGE'), ('btn-warning', 'JAUNE'), ('btn-info', 'BLEU CIEL'), ('btn-dark', 'SOMBRE'), ('btn-light', 'CLAIR'), ('btn-pink', 'ROSE')], default='btn-primary', max_length=20, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Question'),
        ),
    ]
