# Generated by Django 4.2 on 2023-04-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_response_theme_alter_campaign_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='font_size',
            field=models.CharField(choices=[('fs-6', 'Font 6'), ('fs-5', 'Font 5'), ('fs-4', 'Font 4'), ('fs-3', 'Font 3'), ('fs-2', 'Font 2'), ('fs-1', 'Font 1')], default='fs-6', max_length=20, verbose_name='Font Taile'),
        ),
    ]
