# Generated by Django 4.2 on 2023-04-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_response_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='font_size',
            field=models.CharField(choices=[('fs-6', 'Font 1'), ('fs-5', 'Font 2'), ('fs-4', 'Font 3'), ('fs-3', 'Font 4'), ('fs-2', 'Font 5'), ('fs-1', 'Font 6'), ('fs-0', 'Font 7')], default='fs-6', max_length=20, verbose_name='Font Size'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Valeur')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.response')),
            ],
            options={
                'verbose_name': 'Répondre à la question',
            },
        ),
    ]
