# Generated by Django 4.2 on 2023-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_response_font_size_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='value',
            field=models.IntegerField(default=1, verbose_name='Valeur'),
        ),
    ]
